# Generated by Django 5.0.6 on 2024-06-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
