# Generated by Django 5.0.6 on 2024-06-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_genero',
            new_name='genero',
        ),
    ]
