# Generated by Django 5.0.6 on 2024-06-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_rename_genero_usuario_id_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_genero',
            new_name='genero',
        ),
    ]
