# Generated by Django 5.0.6 on 2024-06-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_rename_id_genero_usuario_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='genero',
            new_name='id_genero',
        ),
    ]
